import React from "react";
import { Document, Page, Text, View, StyleSheet, Image, Font } from "@react-pdf/renderer";

const NOTO_SANS_JP =
  "https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-jp@latest/japanese-400-normal.ttf";
const NOTO_SANS_JP_BOLD =
  "https://cdn.jsdelivr.net/fontsource/fonts/noto-sans-jp@latest/japanese-700-normal.ttf";

Font.register({
  family: "NotoSansJP",
  fonts: [
    { src: NOTO_SANS_JP, fontWeight: 400 },
    { src: NOTO_SANS_JP_BOLD, fontWeight: 700 },
  ],
});

export function InsurerPdfDoc(props: { cert: any; qrDataUrl: string; publicUrl: string }) {
  const { cert, qrDataUrl, publicUrl } = props;

  const shopName = cert?.shop_name ?? cert?.tenant_name ?? "SHOP";
  const customerName = cert?.customer_name ?? "";
  const vehicle = cert?.vehicle_info_json?.model ?? cert?.vehicle ?? "";
  const note = cert?.content_free_text ?? "";

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.h1}>施工証明書（保険会社閲覧用）</Text>
          <Text style={styles.small}>{shopName}</Text>
        </View>

        <View style={styles.row}>
          <View style={styles.col}>
            <Text style={styles.label}>お客様</Text>
            <Text>{customerName}</Text>

            <Text style={styles.label}>車両</Text>
            <Text>{vehicle}</Text>

            <Text style={styles.label}>備考</Text>
            <Text>{note}</Text>
          </View>

          <View style={styles.qrBox}>
            {qrDataUrl ? <Image src={qrDataUrl} style={styles.qr} /> : null}
            <Text style={styles.small}>URL</Text>
            <Text style={styles.url}>{publicUrl}</Text>
          </View>
        </View>

        <View style={styles.footer}>
          <Text style={styles.small}>Generated by HOLY-CERT</Text>
        </View>
      </Page>
    </Document>
  );
}

const styles = StyleSheet.create({
  page: {
    padding: 28,
    fontSize: 11,
    fontFamily: "NotoSansJP",
  },
  header: { marginBottom: 14 },
  h1: { fontSize: 16, fontWeight: "bold" },
  row: { flexDirection: "row", gap: 16 },
  col: { flexGrow: 1 },
  label: { marginTop: 10, fontSize: 10, color: "#666" },
  qrBox: { width: 200, borderWidth: 1, borderColor: "#ddd", padding: 10 },
  qr: { width: 160, height: 160, marginBottom: 8 },
  small: { fontSize: 9, color: "#666" },
  url: { fontSize: 9 },
  footer: { position: "absolute", bottom: 20, left: 28, right: 28 },
});